use_frameworks!

target 'ReactiveLevelCache_Example' do
  pod 'ReactiveLevelCache', :path => '../'

  target 'ReactiveLevelCache_Tests' do
    inherit! :search_paths
    pod 'ReactiveLevelCache', :path => '../'

    pod 'Kiwi'
  end
end
